Cesar/config/routes.rb
Rails.application.routes.draw do
  root 'home#dashboard'
  resources :pedidos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Cesar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Cesar/app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :pedidos
end

Cesar/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
end

Cesar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cesar/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nombre)
    end
end

Cesar/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

Cesar/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:producto, :cliente_id)
    end
end

Cesar/app/helpers/application_helper.rb
module ApplicationHelper
end

Cesar/app/helpers/clientes_helper.rb
module ClientesHelper
end

Cesar/app/helpers/home_helper.rb
module HomeHelper
end

Cesar/app/helpers/pedidos_helper.rb
module PedidosHelper
end

Cesar/app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">

<tr>
<th scope="row"><%= cliente.id %></th>
<td><%= cliente.nombre %></td>
<td><%= link_to "Perfil del cliente", cliente %></td>

</tr>



</div>

Cesar/app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Cesar/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Show this cliente", @cliente %> |
  <%= link_to "Back to clientes", clientes_path %>
</div>

Cesar/app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista de Clientes</h1>
<div class="row">
  <div class="col-sm-6">
    <table class="table">
      <div id="clientes">
        <% @clientes.each do |cliente| %>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">Perfil</th>
            </tr>
          </thead>
          <tbody>
            <%= render cliente %>
          </tbody>
        <% end %>
      </div>
    </table>
  </div>
</div>

<%= link_to "Nuevo cliente", new_cliente_path %>

Cesar/app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Back to clientes", clientes_path %>
</div>

Cesar/app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>


  <%= render @cliente %>



<div>
  <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
  <%= link_to "Back to clientes", clientes_path %>

  <%= button_to "Destroy this cliente", @cliente, method: :delete %>
</div>

Cesar/app/views/home/dashboard.html.erb
<div class="jumbotron">
<h1 class="display-4">¡Hola!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="<%= new_cliente_path %>" role="button">Registrarse</a>
</div>

Cesar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cesar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= clientes_path %>">Clientes <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pedidos_path %>">Pedidos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_pedido_path %>">Realizar un pedido</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>

Cesar/app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :producto, style: "display: block" %>
    <%= form.text_field :producto %>
  </div>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.collection_select :cliente_id, Cliente.all, :id, :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Cesar/app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">

<tr>
<th scope="row"><%= pedido.id %></th>
<td><%= pedido.producto %></td>
<td><%= pedido.cliente_id %></td>
<td><%= link_to "Ver pedido", pedido %></td>

</tr>
</div>

Cesar/app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

Cesar/app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div class="row">
  <div class="col-sm-6">
    <table class="table">
      <div id="pedidos">
        <% @pedidos.each do |pedido| %>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">Cliente</th>
              <th scope="col">Detalles</th>
            </tr>
          </thead>
          <tbody>
            <%= render pedido %>
          </tbody>
        <% end %>
      </div>
    </table>
  </div>
</div>

<%= link_to "New pedido", new_pedido_path %>

Cesar/app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

Cesar/app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>